import os, re, subprocess, unicodedata, io, json

RAW = "public/images/plats"
OUT = "public/images/plats-web"
os.makedirs(OUT, exist_ok=True)

def slugify(s):
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode("ascii")
    s = s.lower()
    s = re.sub(r"[^a-z0-9]+", "-", s).strip("-")
    return s

def prettify(name):
    # Title-case each word but keep it simple; preserve accents from source.
    return " ".join(w[:1].upper() + w[1:] if w else w for w in name.split())

files = [f for f in os.listdir(RAW) if f.lower().endswith((".jpg", ".jpeg", ".png"))]

def numkey(f):
    m = re.match(r"\s*(\d+)", f)
    return (int(m.group(1)) if m else 9999, f.lower())

files.sort(key=numkey)

manifest = []
seen = set()
for f in files:
    base = os.path.splitext(f)[0]
    # strip leading "12." or "35," number + separator
    name = re.sub(r"^\s*\d+\s*[.,]\s*", "", base).strip()
    slug = slugify(name)
    if not slug:
        continue
    orig = slug
    n = 2
    while slug in seen:
        slug = f"{orig}-{n}"; n += 1
    seen.add(slug)
    out = os.path.join(OUT, slug + ".webp")
    manifest.append({"slug": slug, "name": prettify(name)})
    if os.path.exists(out):
        continue
    cmd = ["ffmpeg", "-hide_banner", "-loglevel", "error", "-i", os.path.join(RAW, f),
           "-vf", "scale=1500:1000:force_original_aspect_ratio=increase,crop=1500:1000",
           "-c:v", "libwebp", "-quality", "82", "-y", out]
    r = subprocess.run(cmd)
    print(("OK " if r.returncode == 0 else "FAIL ") + slug)

# write TS data file
ts = "// AUTO-GENERATED by scripts/gen_dishes.py — all dish photos, in menu order.\n"
ts += "export type Dish = { slug: string; name: string };\n\n"
ts += "export const DISHES: Dish[] = [\n"
for d in manifest:
    nm = d["name"].replace('"', '\\"')
    ts += f'  {{ slug: "{d["slug"]}", name: "{nm}" }},\n'
ts += "];\n"
os.makedirs("src/data", exist_ok=True)
io.open("src/data/dishes.ts", "w", encoding="utf-8").write(ts)
print("TOTAL", len(manifest))
